import random
n1= str(random.randint(0,9))
n2= str(random.randint(0,9))
n3= str(random.randint(0,9))
m1= str(random.randint(1,6))
m2= str(random.randint(1,6))
m3= str(random.randint(1,6))
m4= str(random.randint(1,6))
print(f"Kolmenumeroinen koodi {n1}{n2}{n3}")
print(f"Nelinumeroinen koodi {m1}{m2}{m3}{m4}")